#!/usr/bin/env php
<?php

if(file_exists(__DIR__ . '/../../autoload.php')) {
  require __DIR__ . '/../../autoload.php';
} else {
  require __DIR__ . '/vendor/autoload.php';
}

ini_set('display_errors', 1);

$dotenv = new Dotenv\Dotenv(__DIR__);
$dotenv->load();

$versionData = json_decode(file_get_contents(__DIR__ . '/project.json'), true);
$cliVersion = $versionData['version'];

echo PHP_EOL;

$app = new Symfony\Component\Console\Application('Y7K CLI', $cliVersion);

$app->add(new \Y7K\Cli\Commands\VersionCommand());
$app->add(new \Y7K\Cli\Commands\BumpCommand());
//$app->add(new \Y7K\Cli\Commands\FetchCommand());
$app->add(new \Y7K\Cli\Commands\LinkCommand());
$app->add(new \Y7K\Cli\Commands\CraftUpdateCommand());
$app->add(new \Y7K\Cli\Commands\ComposerUpdateCommand());

// Install Commands
$app->add(new \Y7K\Cli\Commands\NewCommand());
$app->add(new \Y7K\Cli\Commands\Install\Platform\Craft());
$app->add(new \Y7K\Cli\Commands\Install\Platform\Craft3());
$app->add(new \Y7K\Cli\Commands\Install\Platform\Laravel());
$app->add(new \Y7K\Cli\Commands\Install\Platform\Plain());
$app->add(new \Y7K\Cli\Commands\Install\Resources\Javascript());
$app->add(new \Y7K\Cli\Commands\Install\Resources\Stylesheets());

// Content Commands
$app->add(new \Y7K\Cli\Commands\Content\ContentPullCommand());
$app->add(new \Y7K\Cli\Commands\Content\ContentPushCommand());

// DB Commands
$app->add(new \Y7K\Cli\Commands\Db\DbPullCommand());
$app->add(new \Y7K\Cli\Commands\Db\DbPushCommand());

// Assets Commands
$app->add(new \Y7K\Cli\Commands\Assets\AssetsPullCommand());
$app->add(new \Y7K\Cli\Commands\Assets\AssetsPushCommand());

// Component Commands
$app->add(new \Y7K\Cli\Commands\Components\InstallCommand());
$app->add(new \Y7K\Cli\Commands\Components\UninstallCommand());
$app->add(new \Y7K\Cli\Commands\Components\ListCommand());
$app->add(new \Y7K\Cli\Commands\Components\InfoCommand());


$app->run();
