#!/usr/bin/env php
<?php

if(file_exists(__DIR__ . '/../../autoload.php')) {
  require __DIR__ . '/../../autoload.php';
} else {
  require __DIR__ . '/vendor/autoload.php';
}

ini_set('display_errors', 1);

$app = new Symfony\Component\Console\Application('Y7K CLI', '0.0.0');

$app->add(new \Y7K\Cli\Commands\VersionCommand());
$app->add(new \Y7K\Cli\Commands\BumpCommand());
//$app->add(new \Y7K\Cli\Commands\FetchCommand());
$app->add(new \Y7K\Cli\Commands\LinkCommand());
$app->add(new \Y7K\Cli\Commands\CraftUpdateCommand());

// Install Commands
$app->add(new \Y7K\Cli\Commands\NewCommand());
$app->add(new \Y7K\Cli\Commands\Install\Platform\Craft());
$app->add(new \Y7K\Cli\Commands\Install\Platform\Laravel());
$app->add(new \Y7K\Cli\Commands\Install\Platform\Plain());
$app->add(new \Y7K\Cli\Commands\Install\Resources\Javascript());
$app->add(new \Y7K\Cli\Commands\Install\Resources\Stylesheets());

$app->run();
